// Mock data that follows the DB schema structure and FilledForm type
import type { Template } from "./types";

export const mockTemplate: Template = {
  id: "template-1",
  name: "Employee Onboarding Form",
  description: "Complete onboarding form for new employees",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  sections: [
    {
      id: "section-1",
      title: "Personal Information",
      description: "Please provide your basic personal information",
      order: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      groups: [
        {
          id: "group-1",
          title: "Basic Details",
          order: 1,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-1",
              title: "Full Name",
              label: "What is your full legal name?",
              required: true,
              type: "text" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-2",
              title: "Email Address",
              label: "Enter your email address",
              required: true,
              type: "text" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-3",
              title: "Date of Birth",
              label: "Select your date of birth",
              required: true,
              type: "date" as const,
              order: 3,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
        {
          id: "group-2",
          title: "Contact Information",
          order: 2,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-4",
              title: "Phone Number",
              label: "Enter your phone number",
              required: true,
              type: "text" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-5",
              title: "Emergency Contact",
              label: "Emergency contact phone number",
              required: false,
              type: "text" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
      ],
    },
    {
      id: "section-2",
      title: "Employment Details",
      description: "Information about your role and department",
      order: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      groups: [
        {
          id: "group-3",
          title: "Position Information",
          order: 1,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-6",
              title: "Department",
              label: "Select your department",
              required: true,
              type: "select" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              selectOptions: [
                { value: "Engineering", id: "opt-1" },
                { value: "Marketing", id: "opt-2" },
                { value: "Sales", id: "opt-3" },
                { value: "Human Resources", id: "opt-4" },
                { value: "Finance", id: "opt-5" },
              ],
            },
            {
              id: "q-7",
              title: "Position Title",
              label: "What is your job title?",
              required: true,
              type: "text" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-8",
              title: "Start Date",
              label: "When do you start?",
              required: true,
              type: "date" as const,
              order: 3,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
        {
          id: "group-4",
          title: "Work Preferences",
          order: 2,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-9",
              title: "Remote Work",
              label: "Do you prefer remote work?",
              required: false,
              type: "checkbox" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-10",
              title: "Years of Experience",
              label: "How many years of experience do you have?",
              required: true,
              type: "number" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
      ],
    },
    {
      id: "section-3",
      title: "Documentation",
      description: "Upload required documents",
      order: 3,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      groups: [
        {
          id: "group-5",
          order: 1,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-11",
              title: "Profile Photo",
              label: "Upload a professional profile photo",
              required: true,
              type: "image" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-12",
              title: "ID Document",
              label: "Upload a copy of your ID",
              required: true,
              type: "image" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
      ],
    },
    {
      id: "section-4",
      title: "Additional Information",
      description: "Optional additional details",
      order: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      groups: [
        {
          id: "group-6",
          title: "Preferences",
          order: 1,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          questions: [
            {
              id: "q-13",
              title: "T-Shirt Size",
              label: "Select your t-shirt size",
              required: false,
              type: "select" as const,
              order: 1,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              selectOptions: [
                { value: "XS", id: "size-1" },
                { value: "S", id: "size-2" },
                { value: "M", id: "size-3" },
                { value: "L", id: "size-4" },
                { value: "XL", id: "size-5" },
                { value: "XXL", id: "size-6" },
              ],
            },
            {
              id: "q-14",
              title: "Dietary Restrictions",
              label: "Do you have any dietary restrictions?",
              required: false,
              type: "text" as const,
              order: 2,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            {
              id: "q-15",
              title: "Newsletter Subscription",
              label: "Subscribe to company newsletter",
              required: false,
              type: "checkbox" as const,
              order: 3,
              answer: null,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
          ],
        },
      ],
    },
  ],
};
