FROM node:22.17.0-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json (if exists) and install dependencies
COPY package*.json ./
ARG PAYLOAD_SECRET 
ARG DATABASE_URI

ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
ENV DATABASE_URI=$DATABASE_URI

RUN npm install



# Copy the rest of the source code
COPY . .

# Build TypeScript
RUN npm run build


FROM oven/bun:alpine AS runner

WORKDIR /app

COPY --from=builder /app/package*.json ./ 
COPY --from=builder /app/package-lock.json ./  
COPY --from=builder /app/dist/index.js ./dist/index.js


EXPOSE 3005


# Start the built JS files
CMD ["bun", "dist/index.js"]
