FROM node:22.17.0-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json (if exists) and install dependencies
COPY package*.json ./
COPY package-lock.json ./
RUN npm ci

ARG PAYLOAD_SECRET 
ARG DATABASE_URI

ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
ENV DATABASE_URI=$DATABASE_URI




# Copy the rest of the source code
COPY . .

# Build TypeScript
RUN npm run build

FROM oven/bun:alpine AS runner

WORKDIR /app
ARG PAYLOAD_SECRET 
ARG DATABASE_URI

ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
ENV DATABASE_URI=$DATABASE_URI


COPY --from=builder /app/bundle/index.js /app/index.js
RUN bun install payload@3.62.1 @payloadcms/db-mongodb@3.62.1

EXPOSE 3005

CMD ["bun", "index.js"]
