FROM node:22.17.0-alpine

WORKDIR /app

# Copy package.json and package-lock.json (if exists) and install dependencies
COPY package*.json ./
ARG PAYLOAD_SECRET 
ARG DATABASE_URI

ENV PAYLOAD_SECRET=$PAYLOAD_SECRET
ENV DATABASE_URI=$DATABASE_URI

RUN npm install



# Copy the rest of the source code
COPY . .

# Build TypeScript
RUN npm run build

EXPOSE 3005


# Start the built JS files
CMD ["npm", "run", "start"]
