services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URI=mongodb://localhost:27017
      - PAYLOAD_SECRET=secret
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
